"""
Export a trained PokerCloneNet model as a tournament-compatible bot.

Usage:
    python export_bot.py <model.pt> <output_bot.py> [--hidden-dim 256]

This generates a self-contained bot.py that:
- Subclasses Agent (tournament framework)
- Loads the .pt weights at __init__ time
- Runs inference in act() with valid_actions masking
- Handles all 4 streets + discard correctly
- Uses torch.no_grad() for fast inference (~1-5ms on CPU)
"""

import argparse
import shutil
import sys
from pathlib import Path

# Template for the generated bot.py
BOT_TEMPLATE = '''"""
Tournament bot generated by export_bot.py.
Model: PokerCloneNet (behavioral cloning from human play data).

Allowed libraries: torch, numpy (both in tournament requirements.txt).
"""

from __future__ import annotations

import os
import sys
from collections import Counter
from itertools import combinations

import numpy as np
import torch
import torch.nn as nn

# ── Model architecture (must match training/model.py) ─────────────────────────

FEATURE_DIM = 98
NUM_ACTIONS = 4
NUM_RAISE_BUCKETS = 10
NUM_DISCARD_COMBOS = 10
KEEP_COMBOS = [(i, j) for i in range(5) for j in range(i + 1, 5)]

NUM_RANKS = 9
NUM_SUITS = 3
STRAIGHT_WINDOWS = [
    [8, 0, 1, 2, 3], [0, 1, 2, 3, 4], [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8],
]
ACTION_TYPE_MAP = {"fold": 0, "raise": 1, "check": 2, "call": 3, "discard": 4}


class PokerCloneNet(nn.Module):
    def __init__(self, input_dim=FEATURE_DIM, hidden_dim=HIDDEN_DIM):
        super().__init__()
        self.backbone = nn.Sequential(
            nn.Linear(input_dim, hidden_dim), nn.LayerNorm(hidden_dim), nn.GELU(), nn.Dropout(0.2),
            nn.Linear(hidden_dim, hidden_dim), nn.LayerNorm(hidden_dim), nn.GELU(), nn.Dropout(0.2),
            nn.Linear(hidden_dim, hidden_dim // 2), nn.LayerNorm(hidden_dim // 2), nn.GELU(),
        )
        self.action_head = nn.Sequential(nn.Linear(hidden_dim // 2, 64), nn.GELU(), nn.Linear(64, NUM_ACTIONS))
        self.raise_head = nn.Sequential(nn.Linear(hidden_dim // 2, 64), nn.GELU(), nn.Linear(64, NUM_RAISE_BUCKETS))
        self.discard_head = nn.Sequential(nn.Linear(hidden_dim // 2, 64), nn.GELU(), nn.Linear(64, NUM_DISCARD_COMBOS))

    def forward(self, x):
        s = self.backbone(x)
        return self.action_head(s), self.raise_head(s), self.discard_head(s)


# ── Feature extraction (must mirror training/extract_features.py) ─────────────

def _card_rank(c): return c % NUM_RANKS
def _card_suit(c): return c // NUM_RANKS

def _evaluate_5(cards):
    ranks = [_card_rank(c) for c in cards]
    suits = [_card_suit(c) for c in cards]
    rc = Counter(ranks)
    counts = sorted(rc.values(), reverse=True)
    is_flush = len(set(suits)) == 1
    rs = set(ranks)
    is_straight, si = False, -1
    for i in range(len(STRAIGHT_WINDOWS)-1, -1, -1):
        if all(r in rs for r in STRAIGHT_WINDOWS[i]):
            is_straight, si = True, i
            break
    if is_flush and is_straight: return 8, si / (len(STRAIGHT_WINDOWS)-1)
    if counts[0] == 3 and len(counts) > 1 and counts[1] == 2:
        t = [r for r,c in rc.items() if c==3][0]; p = [r for r,c in rc.items() if c==2][0]
        return 7, (t*NUM_RANKS+p)/(NUM_RANKS**2)
    if is_flush:
        sr = sorted(ranks, reverse=True); tb = sum(r/NUM_RANKS**(i+1) for i,r in enumerate(sr))/NUM_RANKS
        return 6, tb
    if counts[0] == 3: t = [r for r,c in rc.items() if c==3][0]; return 5, t/(NUM_RANKS-1)
    if is_straight: return 4, si/(len(STRAIGHT_WINDOWS)-1)
    if counts[0]==2 and len(counts)>1 and counts[1]==2:
        ps = sorted([r for r,c in rc.items() if c==2], reverse=True)
        k = [r for r,c in rc.items() if c==1][0]
        return 3, (ps[0]*NUM_RANKS**2+ps[1]*NUM_RANKS+k)/(NUM_RANKS**3)
    if counts[0]==2:
        p = [r for r,c in rc.items() if c==2][0]; ks = sorted([r for r,c in rc.items() if c==1], reverse=True)
        k2 = ks[1] if len(ks)>1 else 0
        return 2, (p*NUM_RANKS**2+ks[0]*NUM_RANKS+k2)/(NUM_RANKS**3)
    sr = sorted(ranks, reverse=True); tb = sum(r/NUM_RANKS**(i+1) for i,r in enumerate(sr))/NUM_RANKS
    return 1, tb

def _evaluate_best(hole, comm):
    all_c = [c for c in (hole+comm) if c>=0]
    if len(all_c)<5: return 1, 0.0
    best = (0, 0.0)
    for combo in combinations(all_c, 5):
        r, tb = _evaluate_5(list(combo))
        if r > best[0] or (r==best[0] and tb>best[1]): best = (r, tb)
    return best

def _has_flush_draw(cards):
    sc = Counter(_card_suit(c) for c in cards if c>=0)
    return max(sc.values(), default=0)>=4

def _has_straight_draw(cards):
    rs = set(_card_rank(c) for c in cards if c>=0)
    return any(sum(r in rs for r in w)>=4 for w in STRAIGHT_WINDOWS)

def _count_pairs(cards):
    rc = Counter(_card_rank(c) for c in cards if c>=0)
    return sum(1 for v in rc.values() if v>=2)

def extract_features(obs: dict) -> np.ndarray:
    feat = np.zeros(98, dtype=np.float32)
    my_cards = [c for c in obs.get("my_cards",[]) if c>=0]
    comm = [c for c in obs.get("community_cards",[]) if c>=0]
    opp_disc = [c for c in obs.get("opp_discarded_cards",[]) if c>=0]
    position = "SB" if obs.get("blind_position",0)==0 else "BB"
    street = obs.get("street",0)

    for c in my_cards:
        if 0<=c<27: feat[c]=1
    for c in comm:
        if 0<=c<27: feat[27+c]=1

    if street==0: feat[54]=1
    elif street<=2: feat[55]=1
    else: feat[56]=1
    feat[57] = 1 if position=="SB" else 0

    all_k = my_cards+comm
    if len(my_cards)>=2 and len(comm)>=3:
        hr, tb = _evaluate_best(my_cards, comm)
        feat[58]=(hr-1)/7; feat[64]=tb
    feat[59]=1 if _has_flush_draw(all_k) else 0
    feat[60]=1 if _has_straight_draw(all_k) else 0
    feat[61]=min(_count_pairs(my_cards),2)/2
    feat[62]=1 if any(_card_rank(c)==8 for c in my_cards) else 0
    feat[63]=len(my_cards)/5

    my_bet=obs.get("my_bet",0); opp_bet=obs.get("opp_bet",0)
    pot=obs.get("pot_size",0); my_stack=obs.get("time_left",100)
    to_call=max(0,opp_bet-my_bet); ppc=pot+to_call
    feat[65]=pot/200; feat[66]=my_bet/100; feat[67]=opp_bet/100
    feat[68]=to_call/100; feat[69]=to_call/ppc if ppc>0 else 0
    feat[70]=obs.get("min_raise",2)/100; feat[71]=obs.get("max_raise",100)/100
    feat[72]=(100-my_bet)/100  # approximate stack

    # action history not available in obs — leave as -0.25
    for i in range(10): feat[73+i]=-0.25

    for i, c in enumerate(opp_disc[:10]):
        feat[83+i]=c/26 if c>=0 else 0

    feat[93]=0; feat[94]=0; feat[95]=0; feat[96]=0.5; feat[97]=0
    return feat


# ── Agent implementation ───────────────────────────────────────────────────────

_MODEL_PATH = os.path.join(os.path.dirname(__file__), "MODEL_FILENAME")


class PokerCloneBot:
    """
    Tournament-compatible agent using behavioral cloning.
    """

    def __init__(self):
        self.model = PokerCloneNet()
        state = torch.load(_MODEL_PATH, map_location="cpu", weights_only=True)
        self.model.load_state_dict(state)
        self.model.eval()

    def act(self, observation, reward, terminated, truncated, info) -> tuple:
        """Returns (action_type, raise_amount, keep_card_1, keep_card_2)"""
        if terminated:
            return (2, 0, 0, 1)

        features = extract_features(observation)
        feat_t = torch.tensor(features, dtype=torch.float32).unsqueeze(0)
        valid = observation.get("valid_actions", [1,1,1,1,1])

        with torch.no_grad():
            a_logits, r_logits, d_logits = self.model(feat_t)

        # Discard phase
        if valid[4]:
            combo_idx = d_logits[0].argmax().item()
            k1, k2 = KEEP_COMBOS[combo_idx]
            return (4, 0, k1, k2)

        # Mask invalid actions
        probs = torch.softmax(a_logits[0], dim=0).clone()
        for i in range(4):
            if not valid[i]:
                probs[i] = 0.0
        if probs.sum() == 0:
            return (0, 0, 0, 1)  # fold fallback

        action = probs.argmax().item()

        raise_amount = 0
        if action == 1:  # RAISE
            bucket = r_logits[0].argmax().item()
            min_r = observation.get("min_raise", 2)
            max_r = observation.get("max_raise", 100)
            if max_r <= min_r:
                raise_amount = min_r
            else:
                frac = bucket / 9
                raise_amount = max(min_r, min(int(min_r + frac*(max_r-min_r)), max_r))

        return (action, raise_amount, 0, 1)

    def observe(self, observation, reward, terminated, truncated, info) -> None:
        pass  # No online learning
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("model_pt", help="Path to trained .pt file")
    parser.add_argument("output_py", help="Output bot.py path")
    parser.add_argument("--hidden-dim", type=int, default=256)
    args = parser.parse_args()

    model_path = Path(args.model_pt)
    output_path = Path(args.output_py)

    if not model_path.exists():
        print(f"ERROR: Model file not found: {model_path}")
        sys.exit(1)

    # Copy model weights next to the output bot.py
    model_dest = output_path.parent / model_path.name
    if model_dest != model_path:
        shutil.copy2(model_path, model_dest)
        print(f"Copied model to {model_dest}")

    # Fill template
    code = BOT_TEMPLATE.replace("HIDDEN_DIM", str(args.hidden_dim))
    code = code.replace("MODEL_FILENAME", model_path.name)

    output_path.write_text(code)
    print(f"Generated bot: {output_path}")
    print(f"Model weights: {model_dest}")
    print("\nTo use in tournament:")
    print(f"  Copy {output_path} and {model_dest} to your submission directory")


if __name__ == "__main__":
    main()
